"""empty message

Revision ID: 10bac0f404c
Revises: 1f7e68d5dba
Create Date: 2014-10-29 16:37:49.470820

"""

# revision identifiers, used by Alembic.
revision = '10bac0f404c'
down_revision = '1f7e68d5dba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('style', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'style')
    ### end Alembic commands ###
