"""empty message

Revision ID: 1f7e68d5dba
Revises: 324d22dc6ed
Create Date: 2014-02-20 23:51:31.836909

"""

# revision identifiers, used by Alembic.
revision = '1f7e68d5dba'
down_revision = '324d22dc6ed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('locale', sa.Enum(['es', 'en', 'fr']), server_default='en', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locale')
    ### end Alembic commands ###
