"""empty message

Revision ID: 63a37c3356
Revises: None
Create Date: 2014-02-09 05:21:51.787952

"""

# revision identifiers, used by Alembic.
revision = '63a37c3356'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('modified_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'modified_at')
    ### end Alembic commands ###
